### ISSUE TITLE
[Question]: Trouble connect to ollama

### ISSUE THREAD

**Issue by homegrownhrbs** [infiniflow/ragflow#531] opened 2024-04-24 22:04 UTC
### Describe your problem

hint : 102
Fail to access model(ollama).**ERROR**: [Errno 111] Connection refused

![image](https://github.com/infiniflow/ragflow/assets/92547255/a0cc0df6-4e0a-4cb5-8c50-379ee308eb68)

I double checked that http://localhost:11434/ shows "Ollama is running"
![image](https://github.com/infiniflow/ragflow/assets/92547255/da7e49b7-718c-4b05-ab19-a13580b88ab0)

I'm not sure what to do now, any tips?

**Comment by KevinHuSh** [comment] 2024-04-25 00:48
As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?

**Comment by sensoryfox** [comment] 2024-04-25 01:06
sudo EDITOR=nano systemctl edit ollama.service
[Service]
Environment="OLLAMA_HOST={your_local_ip}"

if changes not accept do in this file: 
sudo nano /etc/systemd/system/ollama.service.d/override.conf

**Comment by calchemist** [comment] 2024-04-25 01:23
I deploy ragflow by docker on my server and ollama also serve on the server.
The baseURL was set http://0.0.0.0:11434 and http://public-IP:11434.
Both of them didn't work.
And suggestions?
HELP!

**Comment by homegrownhrbs** [comment] 2024-04-25 02:09
> As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?

Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?

**Comment by calchemist** [comment] 2024-04-25 04:22
> > As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?
> 
> Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?

On your debian 12 server, run ipconfig, get your ipv4 address, suppose that 10.x.x.8, then set the baseURL as:
http://10.x.x.8:11434

**Comment by calchemist** [comment] 2024-04-25 04:24
> > As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?
> 
> Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?

Since the networks of the ragflow docker and the host server are different, 127.0.0.1 or 0.0.0.0 wouldn't work.

**Comment by KevinHuSh** [comment] 2024-04-25 06:24
> > > As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?
> > 
> > 
> > Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?
> 
> Since the networks of the ragflow docker and the host server are different, 127.0.0.1 or 0.0.0.0 wouldn't work.

Please star RAGFlow.

**Comment by sensoryfox** [comment] 2024-04-25 16:08
I probably didn't write my thought in great detail. The point is that ollama needs to specify the path it will follow and this is done in this file:

/etc/systemd/system/ollama.service.d/override.conf

Until I wrote the path, nothing worked for me.

> sudo EDITOR=nano systemctl edit ollama.service [Service] Environment="OLLAMA_HOST={your_local_ip}"
> 
> if changes not accept do in this file: sudo nano /etc/systemd/system/ollama.service.d/override.conf

**Comment by homegrownhrbs** [comment] 2024-04-25 17:13
> I probably didn't write my thought in great detail. The point is that ollama needs to specify the ip it will follow and this is done in this file:
> 
> /etc/systemd/system/ollama.service.d/override.conf
> 
> Until I wrote the path, nothing worked for me.
> 
> > sudo EDITOR=nano systemctl edit ollama.service [Service] Environment="OLLAMA_HOST={your_local_ip}"
> > if changes not accept do in this file: sudo nano /etc/systemd/system/ollama.service.d/override.conf

I do not have this file/path. I did find /etc/systemd/system/ollama.service but not /etc/systemd/system/ollama.service.d/override.conf 

![image](https://github.com/infiniflow/ragflow/assets/92547255/4aa03e06-2298-4cf6-a3a3-6c282a67ab7f)

This is the content of that ollama.service file
![image](https://github.com/infiniflow/ragflow/assets/92547255/726695d3-d4de-44ed-95bd-7171dbd8687a)

should i try to replace the line  `Environment="PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"`
with `Environment="OLLAMA_HOST=192.168.x.x"`

(By the way, I am super grateful for your help and knowledge, I am brand new to self hosting and I really can't believe how helpful you and the other FOSS/Selfhost community members are. It is really incredible)

**Comment by homegrownhrbs** [comment] 2024-04-25 17:33
> > > As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?
> > 
> > 
> > Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?
> 
> On your debian 12 server, run ipconfig, get your ipv4 address, suppose that 10.x.x.8, then set the baseURL as: http://10.x.x.8:11434

Okay I have done the following: 
1) confirmed my local IP as 192.168.1.x
2) navigated to /user-setting/model in the RAGFLOW UI
3) Entered the "Model Type" as Chat - Model Name as "Ollama or Llama 3" (tried both) - Base url entered http://192.168.x.x:11434 ( the local IP of the Debian Machine running Ollama) 

The Error is persistent. `Fail to access model(Ollama).**ERROR**: [Errno 111] Connection refused`

----
One thing i did notice is that when i visit `http://localhost:11434/` in firefox i see the message "Ollama is running" however, when i navigate to http://192.168.x.x:11434/ I get the "Firefox can’t establish a connection to the server" 

Does this makes me believe that i need to configure ollama to run on my local network somehow?

**Comment by Nehcknarf** [comment] 2024-04-28 10:31
> > > > As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?
> > > 
> > > 
> > > Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?
> > 
> > 
> > On your debian 12 server, run ipconfig, get your ipv4 address, suppose that 10.x.x.8, then set the baseURL as: http://10.x.x.8:11434
> 
> Okay I have done the following:
> 
> 1. confirmed my local IP as 192.168.1.x
> 2. navigated to /user-setting/model in the RAGFLOW UI
> 3. Entered the "Model Type" as Chat - Model Name as "Ollama or Llama 3" (tried both) - Base url entered http://192.168.x.x:11434 ( the local IP of the Debian Machine running Ollama)
> 
> The Error is persistent. `Fail to access model(Ollama).**ERROR**: [Errno 111] Connection refused`
> 
> One thing i did notice is that when i visit `http://localhost:11434/` in firefox i see the message "Ollama is running" however, when i navigate to http://192.168.x.x:11434/ I get the "Firefox can’t establish a connection to the server"
> 
> Does this makes me believe that i need to configure ollama to run on my local network somehow?

Use http://host.docker.internal:11434

**Comment by pengyonglei** [comment] 2024-05-19 13:31
> One thing i did notice is that when i visit `http://localhost:11434/` in firefox i see the message "Ollama is running" however, when i navigate to http://192.168.x.x:11434/ I get the "Firefox can’t establish a connection to the server"

it's works for me, thank you @Nehcknarf

**Comment by cw4219** [comment] 2024-05-28 13:27
Problem:
When attempting to add an Ollama model, I encountered the error Fail to access model(ollama). ERROR: [Errno 111] Connection refused. Upon investigation, I found that while curl http://localhost:11434 worked correctly, curl http://172.16.xx.xxx:11434 did not, indicating the service was only listening on localhost.

Diagnosis:
Running the following command confirmed the issue:

sudo netstat -tuln | grep 11434

Output:

tcp 0 0 127.0.0.1:11434 0.0.0.0:* LISTEN

This indicated that the service was bound to 127.0.0.1 instead of 0.0.0.0.

Solution:
To resolve this, you need to configure the service to listen on all network interfaces by following these steps:

Edit the Ollama service configuration:

sudo systemctl edit ollama.service

Add the environment variable to bind to all interfaces:
In the editor that opens, add the following lines under the [Service] section:

[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"

Reload systemd and restart the Ollama service:

sudo systemctl daemon-reload
sudo systemctl restart ollama

Verify the changes:

sudo netstat -tuln | grep 11434

Output should now show:

tcp6 0 0 :::11434 :::* LISTEN

This configuration change allows the Ollama service to listen on all network interfaces, resolving the connection issue.

**Comment by homegrownhrbs** [comment] 2024-05-30 21:04
> Output:

amazing! thank you, this is exactly what I needed!

**Closed** 2024-05-30 21:04 UTC
Labels: question

**Comment by cse-repon** [comment] 2024-08-12 07:39
> > > > > As your IP adress show, the RAGFlow and Ollama are deployed on the same machine, aren't they?
> > > > 
> > > > 
> > > > Yes they are on the same machine running debian 12, However ollama is not dockerized, maybe that is relevant?
> > > 
> > > 
> > > On your debian 12 server, run ipconfig, get your ipv4 address, suppose that 10.x.x.8, then set the baseURL as: http://10.x.x.8:11434
> > 
> > 
> > Okay I have done the following:
> > 
> > 1. confirmed my local IP as 192.168.1.x
> > 2. navigated to /user-setting/model in the RAGFLOW UI
> > 3. Entered the "Model Type" as Chat - Model Name as "Ollama or Llama 3" (tried both) - Base url entered http://192.168.x.x:11434 ( the local IP of the Debian Machine running Ollama)
> > 
> > The Error is persistent. `Fail to access model(Ollama).**ERROR**: [Errno 111] Connection refused`
> > One thing i did notice is that when i visit `http://localhost:11434/` in firefox i see the message "Ollama is running" however, when i navigate to http://192.168.x.x:11434/ I get the "Firefox can’t establish a connection to the server"
> > Does this makes me believe that i need to configure ollama to run on my local network somehow?
> 
> Use http://host.docker.internal:11434

Wow! Worked like a charm!!! Thank you.

**Comment by Aniwine** [comment] 2024-09-25 02:30
I miss the same issue,and solved it by using http://host.docker.internal:11434/,while Ollama and RAGFlow run on the same machine and just RAGFlow is in Docker.

**Comment by KevinHuSh** [comment] 2024-09-26 01:21
Try this IP: 1722.17.0.1, and check out whether the proxy is on or not. Sometimes, http proxy will block the connections.

**Comment by FelixVerschelde** [comment] 2025-01-20 09:38
> sudo EDITOR=nano systemctl edit ollama.service [Service] Environment="OLLAMA_HOST={your_local_ip}"
> 
> if changes not accept do in this file: sudo nano /etc/systemd/system/ollama.service.d/override.conf

If you set the {your_local_ip} when running everything local to 0.0.0.0:11434 it will work to.

To access the api in RAGFLOW use the command hostname -I and select the first IP that shows.

![Image](https://github.com/user-attachments/assets/00e30c97-0c48-477e-a530-43eb1d5c48d4)

**Comment by superyoung9208** [comment] 2025-01-24 03:31
I fix this problem on my linux computer
1. sudo vim /etc/systemd/system/ollama.service
2. append a new line Environment="OLLAMA_HOST=0.0.0.0:11434"  on [Service] 
3. sudo systemctl daemon-reload
4. sudo systemctl restart ollama
5. the you can use http://host.docker.internal:11434 to add model in ragflow .


my service is this

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/root/bin:/home/zxw/anaconda3/bin:/home/zxw/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin"
Environment="OLLAMA_HOST=0.0.0.0:11434"

**Comment by XxDzonaxX** [comment] 2025-02-12 23:05
i still have this error, my ollama.service file has this line:

[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"

### Edits below this comment will be discarded

and my /etc/systemd/ollama.service looks like this

[Service]
ExecStart=/usr/local/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site>
Environment="OLLAMA_HOST=0.0.0.0:11434"


and now it just keeps loading forever and i still can't accsess the http://host.docker.internal:11434/ url from browser or ragflow.

any help please.

**Comment by rbonazzo-KZ** [comment] 2025-02-14 14:35
On my mac with 
**docker.for.mac.localhost**:11434
it's work fine
