### ISSUE TITLE
[Bug]:the reason of raptor failed  

### ISSUE THREAD

**Issue by adogwangwang** [infiniflow/ragflow#2861] opened 2024-10-16 03:12 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

0.10.0

### Commit ID

 e18f407

### Actual behavior

Start to do RAPTOR (Recursive Abstractive Processing For Tree-Organized Retrieval).
Task has been received.
[ERROR]setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1024,) + inhomogeneous part.       当一篇文章embedding完进入到raptor阶段发生报错,报错信息如上。
**
![image](https://github.com/user-attachments/assets/f66c777a-108c-4e3c-8bd2-1698d86a0926)
**
那么一直卡在这个阶段，应该怎么做？点叉号的话，可以进行问答吗？

### Expected behavior

希望能够找到raptor失败的原因，请大佬看看这段报错是什么意思？这样发生报错的话，希望能有单独重启raptor的按钮，不然全部重新来过的话代价太大。在一个raptor失败，那么这篇文档能不能进行问答？进度条一直卡在一个位置没有动，此时该怎么办？

### Steps to reproduce

```Markdown
一篇文章embedding完进入到raptor阶段过程中发生报错
```

**Comment by KevinHuSh** [comment] 2024-10-16 05:40
You can chat with the generated 4536 chunks.

**Comment by adogwangwang** [comment] 2024-10-16 05:51
> [ERROR]setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1024,) + inhomogeneous part.

感谢您的回复，我想知道最后在raptor阶段报错[ERROR]setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1024,) + inhomogeneous part. 这个报错是什么原因呢？我有两篇文档在raptor阶段都报了这个错，不知道应该怎么调整？希望能得到您的解答

**Comment by KevinHuSh** [comment] 2024-10-16 06:34
This might be caused by embedding, this will be fixed later.

**Comment by adogwangwang** [comment] 2024-10-16 06:39
> This might be caused by embedding, this will be fixed later.

Thank you for your response. I look forward to the fix for this issue.

**Comment by yuzhichang** [comment] 2024-12-02 08:32
@adogwangwang RAGFlow v0.14.1 shall has fixed the embedding issue. Have a try.

**Comment by yuzhichang** [comment] 2024-12-05 04:16
Reusing trunks is tracked by https://github.com/infiniflow/ragflow/issues/3793

**Closed by yuzhichang** 2024-12-05 04:16 UTC
Labels: bug
